# SpaceNet9 Improved Training Configuration - SAR Keypoint Detection
# Enhanced with better loss functions and SAR-specific optimizations

# Experiment settings
exp_name: "spacenet9_improved_unet_sar-003"
exp_dir: "./experiments"
seed: 42
use_wandb: true
wandb_project: "spacenet9"

# Device settings
device: "cuda"

# Data settings
data:
  data_root: "/workspace/project/spacenet9/00_data"
  batch_size: 16
  num_workers: 0
  task: "sar_keypoint_detection"  # Input: optical, Target: SAR keypoints
  regions: ["001", "002", "003"]
  val_ratio: 0.2
  test_ratio: 0.0
  tile_size: 256
  heatmap_sigma: 13

# Model settings
model:
  name: "unet"
  encoder: "resnet34"
  encoder_weights: "imagenet"
  in_channels: 3
  classes: 1

# Enhanced Loss settings optimized for SAR
loss:
  type: "keypoint_detection"
  params:
    loss_type: "mse"
    use_focal: true
    focal_weight: 0.8        # Higher weight due to SAR difficulty
    focal_alpha: 0.8         # Even higher alpha for SAR
    focal_gamma: 3.5         # Higher gamma for SAR complexity
    use_dice: true
    dice_weight: 0.4         # Higher Dice weight for SAR
    dice_smooth: 0.000001
    use_binary_dice: true
    binary_dice_weight: 0.3  # Higher binary Dice weight
    binary_dice_threshold: 0.25  # Even lower threshold for SAR

# Optimizer settings with different learning rate for SAR
optimizer:
  type: "adam"
  lr: 0.00005              # Lower learning rate for SAR stability
  weight_decay: 0.0001       # Higher weight decay for SAR regularization

# Learning rate scheduler
scheduler:
  type: "cosine"
  T_max: 100
  eta_min: 0.0000001            # Lower minimum LR for SAR

# Training settings
training:
  epochs: 100
  gradient_clip: 0.5       # Lower gradient clipping for SAR
  early_stopping_patience: 30  # More patience for SAR
  early_stopping_delta: 0.0001
  max_checkpoints: 5
  resume: null
  vis_interval: 10

# Evaluation settings optimized for SAR
evaluation:
  pixel_error_threshold: 10.0
  post_process:
    threshold: 0.25        # Lower threshold for SAR
    nms_radius: 7          # Larger NMS radius for SAR
    max_keypoints: 30      # Fewer max keypoints for SAR

# SAR-optimized augmentation settings
augmentation:
  random_rotate90: 0.5
  flip: 0.5
  shift_scale_rotate:
    shift_limit: 0.0625
    scale_limit: 0.05      # Reduced scale variation for optical
    rotate_limit: 10       # Reduced rotation for optical
    p: 0.4
  brightness_contrast:
    brightness_limit: 0.2  # Standard for optical images
    contrast_limit: 0.2
    p: 0.5
  noise:
    var_limit: [10.0, 30.0]  # Moderate noise for optical
    p: 0.3
  blur:
    blur_limit: [3, 7]     # Standard blur for optical
    p: 0.3